"""initshell-path

Revision ID: 045f9e664c54
Revises: 1df99f87c208
Create Date: 2019-11-11 08:06:28.076987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '045f9e664c54'
down_revision = '1df99f87c208'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_channels', sa.Column('remark', sa.Text(length=500), nullable=True))
    op.add_column('t_games', sa.Column('local_initshell_path', sa.String(length=200), nullable=True))
    op.add_column('t_games', sa.Column('remote_initshell_path', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('t_games', 'remote_initshell_path')
    op.drop_column('t_games', 'local_initshell_path')
    op.drop_column('t_channels', 'remark')
    # ### end Alembic commands ###
