"""重构游戏、渠道、区服数据库关系

Revision ID: 5555da5aa22c
Revises: 045f9e664c54
Create Date: 2019-11-12 03:32:41.671028

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5555da5aa22c'
down_revision = '045f9e664c54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_zones', sa.Column('channel_id', sa.Integer(), nullable=True))
    op.drop_constraint('t_zones_ibfk_1', 't_zones', type_='foreignkey')
    op.create_foreign_key(None, 't_zones', 't_channels', ['channel_id'], ['id'])
    op.drop_column('t_zones', 'game_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_zones', sa.Column('game_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 't_zones', type_='foreignkey')
    op.create_foreign_key('t_zones_ibfk_1', 't_zones', 't_games', ['game_id'], ['id'])
    op.drop_column('t_zones', 'channel_id')
    # ### end Alembic commands ###
