"""完善程序更新数据库字段v3

Revision ID: 56ced219286d
Revises: d4d2b7b81cad
Create Date: 2019-11-20 11:47:52.734759

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '56ced219286d'
down_revision = 'd4d2b7b81cad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('t_channels', 'remark',
               existing_type=mysql.TEXT(),
               type_=sa.Text(length=500),
               existing_nullable=True)
    op.add_column('t_games', sa.Column('remote_cold_update_shell_path', sa.String(length=200), nullable=True))
    op.add_column('t_games', sa.Column('remote_hot_update_shell_path', sa.String(length=200), nullable=True))
    op.drop_column('t_games', 'remote_update_shell_path')
    op.alter_column('t_user', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('t_user', 'is_active',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.add_column('t_games', sa.Column('remote_update_shell_path', mysql.VARCHAR(length=200), nullable=True))
    op.drop_column('t_games', 'remote_hot_update_shell_path')
    op.drop_column('t_games', 'remote_cold_update_shell_path')
    op.alter_column('t_channels', 'remark',
               existing_type=sa.Text(length=500),
               type_=mysql.TEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
