"""增加启停服脚本本地远端保存路径字段

Revision ID: 58f95fc36cff
Revises: 56ced219286d
Create Date: 2019-11-23 15:30:48.671999

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '58f95fc36cff'
down_revision = '56ced219286d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('t_channels', 'remark',
               existing_type=mysql.TEXT(),
               type_=sa.Text(length=500),
               existing_nullable=True)
    op.add_column('t_games', sa.Column('local_startservice_shell_path', sa.String(length=200), nullable=True))
    op.add_column('t_games', sa.Column('local_stopservice_shell_path', sa.String(length=200), nullable=True))
    op.add_column('t_games', sa.Column('remote_startservice_shell_path', sa.String(length=200), nullable=True))
    op.add_column('t_games', sa.Column('remote_stopservice_shell_path', sa.String(length=200), nullable=True))
    op.alter_column('t_user', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('t_user', 'is_active',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.drop_column('t_games', 'remote_stopservice_shell_path')
    op.drop_column('t_games', 'remote_startservice_shell_path')
    op.drop_column('t_games', 'local_stopservice_shell_path')
    op.drop_column('t_games', 'local_startservice_shell_path')
    op.alter_column('t_channels', 'remark',
               existing_type=sa.Text(length=500),
               type_=mysql.TEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
