"""重构游戏渠道区服三表关系

Revision ID: 678b02f1d7a1
Revises: bada9f45f2fa
Create Date: 2019-11-12 12:22:32.713634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '678b02f1d7a1'
down_revision = 'bada9f45f2fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('membership',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['t_channels.id'], ),
    sa.ForeignKeyConstraint(['game_id'], ['t_games.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['t_zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('membership')
    # ### end Alembic commands ###
