"""重构游戏渠道区服三表关系

Revision ID: bada9f45f2fa
Revises: f05fea79c8a2
Create Date: 2019-11-12 11:48:22.554792

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bada9f45f2fa'
down_revision = 'f05fea79c8a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('membership',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['t_channels.id'], ),
    sa.ForeignKeyConstraint(['game_id'], ['t_games.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['t_zones.id'], ),
    sa.PrimaryKeyConstraint('game_id', 'channel_id', 'zone_id')
    )
    op.drop_table('association_game_channel')
    op.drop_constraint('t_zones_ibfk_1', 't_zones', type_='foreignkey')
    op.drop_column('t_zones', 'channel_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_zones', sa.Column('channel_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('t_zones_ibfk_1', 't_zones', 't_channels', ['channel_id'], ['id'])
    op.create_table('association_game_channel',
    sa.Column('game_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('channel_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['t_channels.id'], name='association_game_channel_ibfk_1'),
    sa.ForeignKeyConstraint(['game_id'], ['t_games.id'], name='association_game_channel_ibfk_2'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_table('membership')
    # ### end Alembic commands ###
