"""zone表增加状态字段

Revision ID: d7a1debd80d3
Revises: caf0448634a5
Create Date: 2019-12-02 03:21:50.535600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7a1debd80d3'
down_revision = 'caf0448634a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_zones', sa.Column('status', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('t_zones', 'status')
    # ### end Alembic commands ###
