"""修改游戏表字段长度

Revision ID: de91c3c508a7
Revises: fa7edb5f6d60
Create Date: 2019-11-18 12:37:12.627793

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'de91c3c508a7'
down_revision = 'fa7edb5f6d60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('t_channels', 'remark',
               existing_type=mysql.TEXT(),
               type_=sa.Text(length=500),
               existing_nullable=True)
    op.alter_column('t_games', 'local_open_service_pkg_path',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.alter_column('t_games', 'local_open_service_shell_path',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.alter_column('t_games', 'remote_open_service_pkg_path',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.alter_column('t_games', 'remote_open_service_shell_path',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.alter_column('t_games', 'remote_unzip_path',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.alter_column('t_user', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('t_user', 'is_active',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('t_games', 'remote_unzip_path',
               existing_type=sa.String(length=200),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('t_games', 'remote_open_service_shell_path',
               existing_type=sa.String(length=200),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('t_games', 'remote_open_service_pkg_path',
               existing_type=sa.String(length=200),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('t_games', 'local_open_service_shell_path',
               existing_type=sa.String(length=200),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('t_games', 'local_open_service_pkg_path',
               existing_type=sa.String(length=200),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('t_channels', 'remark',
               existing_type=sa.Text(length=500),
               type_=mysql.TEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
