"""完善区服表字段

Revision ID: f05fea79c8a2
Revises: 5555da5aa22c
Create Date: 2019-11-12 06:59:33.547231

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f05fea79c8a2'
down_revision = '5555da5aa22c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_zones', sa.Column('db_A', sa.String(length=10), nullable=True))
    op.add_column('t_zones', sa.Column('db_B', sa.String(length=10), nullable=True))
    op.add_column('t_zones', sa.Column('db_C', sa.String(length=10), nullable=True))
    op.add_column('t_zones', sa.Column('dblink', sa.String(length=30), nullable=True))
    op.add_column('t_zones', sa.Column('dbport', sa.Integer(), nullable=True))
    op.add_column('t_zones', sa.Column('zoneip', sa.String(length=30), nullable=True))
    op.add_column('t_zones', sa.Column('zonename', sa.String(length=30), nullable=True))
    op.add_column('t_zones', sa.Column('zonenum', sa.String(length=30), nullable=True))
    op.drop_column('t_zones', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_zones', sa.Column('name', mysql.VARCHAR(length=30), nullable=True))
    op.drop_column('t_zones', 'zonenum')
    op.drop_column('t_zones', 'zonename')
    op.drop_column('t_zones', 'zoneip')
    op.drop_column('t_zones', 'dbport')
    op.drop_column('t_zones', 'dblink')
    op.drop_column('t_zones', 'db_C')
    op.drop_column('t_zones', 'db_B')
    op.drop_column('t_zones', 'db_A')
    # ### end Alembic commands ###
