"""一对多自关联

Revision ID: f9354de648dd
Revises: 69e65dfc01be
Create Date: 2019-12-02 06:55:04.341043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9354de648dd'
down_revision = '69e65dfc01be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_zones', sa.Column('parant_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 't_zones', 't_zones', ['parant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 't_zones', type_='foreignkey')
    op.drop_column('t_zones', 'parant_id')
    # ### end Alembic commands ###
