"""添加新服搭建数据库字段

Revision ID: fa7edb5f6d60
Revises: 8e37c1deaa77
Create Date: 2019-11-15 11:55:18.123418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa7edb5f6d60'
down_revision = '8e37c1deaa77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_games', sa.Column('local_open_service_pkg_path', sa.String(length=50), nullable=True))
    op.add_column('t_games', sa.Column('local_open_service_shell_path', sa.String(length=50), nullable=True))
    op.add_column('t_games', sa.Column('remote_open_service_pkg_path', sa.String(length=50), nullable=True))
    op.add_column('t_games', sa.Column('remote_open_service_shell_path', sa.String(length=50), nullable=True))
    op.add_column('t_games', sa.Column('remote_unzip_path', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('t_games', 'remote_unzip_path')
    op.drop_column('t_games', 'remote_open_service_shell_path')
    op.drop_column('t_games', 'remote_open_service_pkg_path')
    op.drop_column('t_games', 'local_open_service_shell_path')
    op.drop_column('t_games', 'local_open_service_pkg_path')
    # ### end Alembic commands ###
